-- Thai Order / NIGHTOPS chat ingestion tables
-- Run once in Supabase SQL Editor. The n8n processors upsert with dedupe_key.

create table if not exists public.chat_customer_messages (
  id bigint generated by default as identity primary key,
  source_message_id text,
  dedupe_key text not null unique,
  page_id text not null,
  page_name text,
  conversation_key text not null,
  customer_id text,
  customer_name text,
  speaker_type text not null default 'customer' check (speaker_type = 'customer'),
  side text not null default 'left' check (side = 'left'),
  message_text text,
  message_type text not null default 'text',
  attachments_json jsonb not null default '[]'::jsonb,
  image_urls jsonb not null default '[]'::jsonb,
  has_image boolean not null default false,
  attachment_count integer not null default 0,
  shares_json jsonb,
  sticker_json jsonb,
  occurred_at timestamptz,
  source_created_at timestamptz,
  synced_at timestamptz not null default now(),
  raw_payload jsonb
);

create table if not exists public.chat_page_messages (
  id bigint generated by default as identity primary key,
  source_message_id text,
  dedupe_key text not null unique,
  page_id text not null,
  page_name text,
  conversation_key text not null,
  page_sender_id text,
  page_sender_name text,
  speaker_type text not null default 'page' check (speaker_type = 'page'),
  side text not null default 'right' check (side = 'right'),
  message_text text,
  message_type text not null default 'text',
  attachments_json jsonb not null default '[]'::jsonb,
  image_urls jsonb not null default '[]'::jsonb,
  has_image boolean not null default false,
  attachment_count integer not null default 0,
  shares_json jsonb,
  sticker_json jsonb,
  occurred_at timestamptz,
  source_created_at timestamptz,
  synced_at timestamptz not null default now(),
  raw_payload jsonb
);

create index if not exists chat_customer_messages_thread_idx on public.chat_customer_messages (page_id, conversation_key, occurred_at desc);
create index if not exists chat_page_messages_thread_idx on public.chat_page_messages (page_id, conversation_key, occurred_at desc);
create index if not exists chat_customer_messages_synced_idx on public.chat_customer_messages (synced_at desc);
create index if not exists chat_page_messages_synced_idx on public.chat_page_messages (synced_at desc);

-- n8n uses service-role REST Upsert. Keep browser reads server-side only.
-- If RLS is enabled in your project, enable it and grant no public/anon access.
-- The NIGHTOPS server reads these tables with SUPABASE_SERVICE_ROLE_KEY.
