-- NIGHTOPS customer chat evidence ledger
-- This table is separate from the Chat UI tables and from order evidence.
-- Run once in Supabase SQL Editor.

create table if not exists public.chat_customer_evidence (
  id bigint generated by default as identity primary key,
  source_message_id text,
  dedupe_key text not null unique,
  page_id text not null,
  page_name text,
  conversation_key text not null,
  customer_id text,
  customer_name text,
  sender_id text not null,
  sender_name text,
  speaker_type text not null default 'customer' check (speaker_type = 'customer'),
  message_text text,
  message_type text not null default 'text',
  attachments_json jsonb not null default '[]'::jsonb,
  image_urls jsonb not null default '[]'::jsonb,
  has_image boolean not null default false,
  attachment_count integer not null default 0,
  shares_json jsonb,
  sticker_json jsonb,
  occurred_at timestamptz,
  source_created_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  raw_payload jsonb,
  ingestion_source text not null default 'meta_n8n_polling'
);

create index if not exists chat_customer_evidence_thread_idx
  on public.chat_customer_evidence (page_id, conversation_key, occurred_at desc);
create index if not exists chat_customer_evidence_customer_idx
  on public.chat_customer_evidence (customer_id, occurred_at desc);
create index if not exists chat_customer_evidence_source_idx
  on public.chat_customer_evidence (source_message_id);
create index if not exists chat_customer_evidence_seen_idx
  on public.chat_customer_evidence (last_seen_at desc);

-- n8n should use service-role REST Upsert with conflict column dedupe_key.
-- Keep this table append-only from the browser: no public/anon write access.
-- If RLS is enabled, keep browser access disabled and read through the server only.

comment on table public.chat_customer_evidence is
  'Immutable-ish audit ledger of raw customer Facebook messages, separate from order evidence and Chat UI projections';
comment on column public.chat_customer_evidence.dedupe_key is
  'Stable idempotency key; prefer meta:<source_message_id>'; 
comment on column public.chat_customer_evidence.raw_payload is
  'Original normalized Meta/n8n payload retained for investigation';
