import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { AtSign, Check, CircleUserRound, Clock3, Hash, MessageCircle, RefreshCw, Search, Send, Sparkles, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

function timeLabel(value: string | null | undefined) {
  if (!value) return "—";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("th-TH", { hour: "2-digit", minute: "2-digit" }).format(date);
}

export default function ChatHub() {
  const [search, setSearch] = useState("");
  const [selectedKey, setSelectedKey] = useState<string | null>(null);
  const threadsQuery = trpc.orders.threads.useQuery({ search: search || undefined }, { refetchInterval: 30_000 });
  const threads = threadsQuery.data ?? [];
  const selected = threads.find(thread => thread.key === selectedKey) ?? threads[0];
  const pages = useMemo(() => Array.from(new Map(threads.map(thread => [thread.pageName, threads.filter(item => item.pageName === thread.pageName).length])).entries()).sort((a, b) => b[1] - a[1]), [threads]);
  useEffect(() => { if (!selectedKey && threads[0]) setSelectedKey(threads[0].key); }, [threads, selectedKey]);

  return <div className="min-h-[calc(100vh-2rem)] bg-[#09070d] text-white"><div className="mx-auto max-w-[1600px] space-y-5 p-2 sm:p-4 lg:p-6">
    <header className="relative overflow-hidden rounded-3xl border border-violet-500/20 bg-[#100c19] px-6 py-7 shadow-2xl shadow-violet-950/20 sm:px-8"><div className="pointer-events-none absolute -right-24 -top-36 h-80 w-80 rounded-full bg-fuchsia-600/20 blur-3xl" /><div className="pointer-events-none absolute bottom-0 left-1/3 h-40 w-72 rounded-full bg-violet-600/10 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.28em] text-fuchsia-300"><Sparkles className="h-4 w-4" /> NIGHTOPS · PAGE CHAT HUB</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">รวมแชทเพจ</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-violet-100/55">รวมกลุ่มการสนทนาจากข้อมูลจริงในออเดอร์ แยกตามเพจและ thread เพื่อให้เห็นบริบทลูกค้าก่อนจัดการออเดอร์</p></div><div className="flex flex-wrap items-center gap-2"><Badge className="border border-emerald-400/30 bg-emerald-400/10 text-emerald-300"><span className="mr-2 h-1.5 w-1.5 rounded-full bg-emerald-400" /> LIVE THREADS</Badge><Button variant="outline" size="sm" onClick={() => threadsQuery.refetch()} className="border-violet-400/20 bg-violet-400/5 text-violet-100 hover:bg-violet-400/10"><RefreshCw className={`mr-2 h-3.5 w-3.5 ${threadsQuery.isFetching ? "animate-spin" : ""}`} /> รีเฟรช</Button></div></div></header>

    <div className="grid gap-5 lg:grid-cols-[250px_minmax(0,1fr)_360px]"><Card className="rounded-3xl border-violet-500/15 bg-[#100d15] shadow-xl shadow-violet-950/10"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Users className="h-4 w-4 text-fuchsia-300" /> เพจทั้งหมด <span className="ml-auto text-xs font-normal text-violet-100/40">{pages.length}</span></CardTitle></CardHeader><CardContent className="space-y-1 pt-0">{pages.map(([page, count], index) => <button key={page} onClick={() => setSearch(page)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left hover:bg-violet-400/10"><span className={`flex h-8 w-8 items-center justify-center rounded-lg text-xs font-semibold ${index % 3 === 0 ? "bg-fuchsia-500/15 text-fuchsia-200" : index % 3 === 1 ? "bg-violet-500/15 text-violet-200" : "bg-indigo-500/15 text-indigo-200"}`}>{String(page).slice(0, 2).toUpperCase()}</span><span className="min-w-0 flex-1 truncate text-sm text-violet-50/80">{page}</span><span className="text-xs text-violet-100/35">{count}</span></button>)}{pages.length === 0 && <p className="p-3 text-sm text-violet-100/35">ยังไม่พบชื่อเพจ</p>}<div className="mt-5 rounded-2xl border border-fuchsia-400/10 bg-fuchsia-400/[0.03] p-4 text-xs leading-5 text-violet-100/45"><AtSign className="mb-2 h-4 w-4 text-fuchsia-300" />แหล่งข้อมูลนี้อ่านจาก `bb_order_items_fix` เป็นหลัก เพื่อให้ได้ข้อมูลลูกค้าที่ครบกว่า</div></CardContent></Card>

      <Card className="overflow-hidden rounded-3xl border-violet-500/15 bg-[#100d15] shadow-xl shadow-violet-950/10"><CardHeader className="border-b border-violet-500/10 pb-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="text-base">ห้องสนทนาล่าสุด</CardTitle><p className="mt-1 text-xs text-violet-100/40">{threads.length.toLocaleString("th-TH")} threads จากออเดอร์จริง</p></div><div className="relative sm:w-52"><Search className="absolute left-3 top-2.5 h-4 w-4 text-violet-100/30" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="ค้นหาเพจ/ลูกค้า…" className="rounded-xl border-violet-500/15 bg-black/20 pl-9 text-white placeholder:text-violet-100/25 focus-visible:ring-fuchsia-400" /></div></div></CardHeader><CardContent className="max-h-[690px] overflow-y-auto p-3">{threadsQuery.isLoading ? <div className="flex items-center justify-center gap-2 p-12 text-sm text-violet-100/40"><RefreshCw className="h-4 w-4 animate-spin" />กำลังรวม thread…</div> : threads.length === 0 ? <div className="p-12 text-center text-sm text-violet-100/40"><MessageCircle className="mx-auto mb-3 h-8 w-8 text-violet-100/15" />ไม่พบห้องสนทนา</div> : threads.map(thread => <button key={thread.key} onClick={() => setSelectedKey(thread.key)} className={`mb-2 flex w-full items-start gap-3 rounded-2xl border p-4 text-left transition ${selected?.key === thread.key ? "border-fuchsia-400/50 bg-fuchsia-400/[0.06]" : "border-violet-500/10 bg-black/10 hover:border-violet-400/25 hover:bg-violet-400/[0.03]"}`}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-fuchsia-500/20 to-violet-500/20 text-xs font-semibold text-fuchsia-200">{thread.pageName.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold text-violet-50">{thread.customerName || "ไม่ระบุลูกค้า"}</p><Badge variant="outline" className="border-violet-400/20 bg-violet-400/5 px-2 py-0.5 text-[10px] text-violet-200">{thread.pageName}</Badge></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-violet-100/45">{thread.preview}</p><div className="mt-2 flex items-center gap-3 text-[10px] text-violet-100/30"><span className="flex items-center gap-1"><Hash className="h-3 w-3" />{thread.orderCount} ออเดอร์</span><span className="flex items-center gap-1"><Clock3 className="h-3 w-3" />{timeLabel(thread.latestAt)}</span></div></div></button>)}</CardContent></Card>

      <Card className="overflow-hidden rounded-3xl border-violet-500/15 bg-[#100d15] shadow-xl shadow-violet-950/10 lg:sticky lg:top-5 lg:self-start"><CardHeader className="border-b border-violet-500/10 pb-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-fuchsia-500/10 p-2 text-fuchsia-300"><MessageCircle className="h-4 w-4" /></div><div className="min-w-0"><p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-fuchsia-300">THREAD INSPECTOR</p><CardTitle className="truncate text-base">{selected?.customerName || "เลือกห้องสนทนา"}</CardTitle></div></div></CardHeader><CardContent className="space-y-4 p-4">{selected ? <><div className="rounded-2xl border border-violet-400/10 bg-black/20 p-4"><div className="flex items-center justify-between"><span className="text-xs text-violet-100/40">เพจต้นทาง</span><Badge className="border border-fuchsia-400/20 bg-fuchsia-400/10 text-fuchsia-200">{selected.pageName}</Badge></div><div className="mt-4 flex items-center gap-3 text-sm text-violet-50/80"><CircleUserRound className="h-4 w-4 text-violet-300" />{selected.customerName || "ไม่ระบุชื่อ"}</div><p className="mt-3 text-xs leading-5 text-violet-100/45">{selected.preview}</p></div><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-100/35">ออเดอร์ใน thread</p><div className="space-y-2">{selected.orders.slice(0, 8).map(order => <div key={order.order_number} className="rounded-xl border border-violet-500/10 bg-black/20 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[11px] text-violet-200">{order.order_number}</span><span className="text-[10px] text-violet-100/35">{timeLabel(order.created_at || order.order_time)}</span></div><p className="mt-2 truncate text-xs text-violet-50/70">{order.display_for_packer || order.th_name || order.sku || "ไม่ระบุสินค้า"}</p><div className="mt-2 flex items-center gap-2 text-[10px] text-violet-100/35"><Send className="h-3 w-3" /> Telegram: {order.telegram_status || "ยังไม่ระบุ"}</div></div>)}</div></div><Button disabled className="w-full rounded-xl bg-gradient-to-r from-fuchsia-600 to-violet-600 text-white opacity-60"><Send className="mr-2 h-4 w-4" /> เปิดการส่งเมื่อเชื่อม Atomic Claim</Button></> : <div className="py-16 text-center text-sm text-violet-100/35">เลือกห้องสนทนาเพื่อดูรายละเอียด</div>}</CardContent></Card>
    </div><footer className="flex items-center gap-2 px-2 text-[11px] text-violet-100/30"><MessageCircle className="h-3.5 w-3.5" />จัดกลุ่มจาก page_name + thread_id และใช้ bb_order_items_fix เป็นข้อมูลหลัก</footer>
  </div></div>;
}
