import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Download, MessageCircle, RefreshCw, Search, Users } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

function todayBangkok() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }
function timeLabel(value: string | null) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("th-TH", { timeZone: "Asia/Bangkok", hour: "2-digit", minute: "2-digit" }).format(date); }
function csvCell(value: unknown) { return `"${String(value ?? "").replace(/"/g, '""').replace(/\r?\n/g, " ")}"`; }

export default function DailyChatSummary() {
  const [date, setDate] = useState(todayBangkok);
  const [search, setSearch] = useState("");
  const query = trpc.orders.dailyChatSummary.useQuery({ date }, { refetchInterval: 60_000 });
  const threads = (query.data?.threads ?? []).filter(thread => `${thread.customerName} ${thread.pageName} ${thread.threadId} ${thread.snippets.join(" ")}`.toLowerCase().includes(search.toLowerCase()));
  const exportCsv = () => { const header = ["วันที่", "ชื่อลูกค้า", "Customer ID", "เพจ", "Page ID", "Thread ID", "ข้อความลูกค้า", "ข้อความเพจ", "สัญญาณออเดอร์", "ข้อความตัวอย่าง", "เวลาล่าสุด"]; const rows = threads.map(thread => [date, thread.customerName, thread.customerId, thread.pageName, thread.pageId, thread.threadId, thread.customerMessages, thread.pageMessages, thread.orderSignals, thread.snippets.join(" | "), thread.latestAt]); const csv = "\uFEFF" + [header, ...rows].map(row => row.map(csvCell).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `nightops-chat-orders-${date}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="min-h-[calc(100vh-2rem)] space-y-5 bg-[#09070d] p-2 text-white sm:p-4 lg:p-6">
    <header className="rounded-3xl border border-violet-500/20 bg-[#100c19] p-6 shadow-2xl shadow-violet-950/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-fuchsia-300"><CalendarDays className="h-4 w-4" /> NIGHTOPS · DAILY CHAT ORDER SUMMARY</div><h1 className="mt-3 text-3xl font-semibold">สรุปออเดอร์จากห้องแชทรายวัน</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-violet-100/55">รวมข้อความจากฝั่งลูกค้าและเพจโดยตรง ไม่ต้องรอหรือต่อกับตารางออเดอร์ ระบบจัดกลุ่มตามเพจและห้องสนทนา แล้วทำเครื่องหมายที่มี COD หรือสัญญาณการสั่งซื้อ</p></div><div className="flex flex-wrap gap-2"><Input type="date" value={date} onChange={event => setDate(event.target.value)} className="w-40 border-violet-400/20 bg-black/20 text-white" /><Button variant="outline" onClick={exportCsv} disabled={!threads.length} className="border-emerald-400/20 bg-emerald-400/5 text-emerald-200"><Download className="mr-2 h-4 w-4" />Export CSV</Button><Button variant="outline" onClick={() => query.refetch()} className="border-violet-400/20 bg-violet-400/5 text-violet-100"><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} />รีเฟรช</Button><Link href="/chats"><Button className="bg-gradient-to-r from-fuchsia-600 to-violet-600">เปิดห้องแชท</Button></Link></div></div></header>
    <Card className="border-amber-400/20 bg-amber-950/10"><CardContent className="p-4 text-xs leading-6 text-amber-100/70"><span className="font-semibold text-amber-200">หมายเหตุ:</span> ตัวเลข “สัญญาณออเดอร์” เป็นการคัดกรองจากข้อความ เช่น สั่ง, รับ, คอต, ที่อยู่, เบอร์, ปลายทาง และยังไม่ใช่ใบสั่งซื้อที่ยืนยันแล้ว ควรเปิดห้องแชทตรวจและสร้างออเดอร์ต่อ</CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="ข้อความทั้งหมด" value={query.data?.totalMessages ?? 0} icon={<MessageCircle className="h-5 w-5" />} /><Stat label="ข้อความลูกค้า" value={query.data?.customerMessages ?? 0} tone="text-fuchsia-300" icon={<Users className="h-5 w-5" />} /><Stat label="ข้อความเพจ" value={query.data?.pageMessages ?? 0} tone="text-violet-300" icon={<MessageCircle className="h-5 w-5" />} /><Stat label="ห้องทั้งหมด" value={query.data?.threadCount ?? 0} tone="text-emerald-300" icon={<Users className="h-5 w-5" />} /><Stat label="ห้องมีสัญญาณสั่งซื้อ" value={query.data?.orderSignalThreads ?? 0} tone="text-amber-300" icon={<Search className="h-5 w-5" />} /></div>
    <Card className="rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">ห้องที่พบในวันที่ {date}</CardTitle><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="ค้นหาลูกค้า / เพจ / ข้อความ" className="w-full border-violet-500/15 bg-black/20 text-white placeholder:text-violet-100/25 sm:w-72" /></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="border-b border-violet-500/10 text-violet-100/35"><tr><th className="p-3">ลูกค้า</th><th className="p-3">เพจ</th><th className="p-3">ห้อง</th><th className="p-3">ลูกค้า / เพจ</th><th className="p-3">สัญญาณสั่งซื้อ</th><th className="p-3">ข้อความตัวอย่าง</th><th className="p-3">เวลา</th></tr></thead><tbody>{threads.map(thread => <tr key={`${thread.pageId}-${thread.threadId}`} className="border-b border-violet-500/[0.06] align-top"><td className="p-3 font-medium text-white">{thread.customerName}<p className="font-mono text-[10px] text-violet-100/30">{thread.customerId || "—"}</p></td><td className="p-3 text-fuchsia-200">{thread.pageName}</td><td className="p-3 font-mono text-violet-100/45">{thread.threadId}</td><td className="p-3"><span className="text-fuchsia-200">{thread.customerMessages}</span><span className="text-violet-100/35"> / </span><span className="text-violet-200">{thread.pageMessages}</span></td><td className="p-3"><Badge className={thread.orderSignals ? "border-amber-400/20 bg-amber-400/10 text-amber-200" : "border-violet-400/20 bg-violet-400/10 text-violet-200"}>{thread.orderSignals ? `${thread.orderSignals} จุด` : "ไม่พบ"}</Badge></td><td className="max-w-sm p-3 text-violet-100/65">{thread.snippets.length ? thread.snippets.map((snippet, index) => <p key={index} className="mb-1 line-clamp-2">{snippet}</p>) : "ไม่มีข้อความลูกค้าที่เข้าเกณฑ์"}</td><td className="p-3 text-violet-100/50">{timeLabel(thread.latestAt)}</td></tr>)}</tbody></table></div>{query.isLoading ? <p className="p-8 text-center text-sm text-violet-100/40">กำลังรวมข้อความแชท…</p> : null}{!query.isLoading && !threads.length ? <p className="p-8 text-center text-sm text-violet-100/40">ไม่พบข้อความในวันที่เลือก</p> : null}</CardContent></Card>
  </div>;
}

function Stat({ label, value, tone = "text-white", icon }: { label: string; value: number; tone?: string; icon: React.ReactNode }) { return <Card className="rounded-2xl border-violet-500/15 bg-[#100d15]"><CardContent className="flex items-center gap-3 p-4"><div className={`rounded-xl bg-violet-500/10 p-2.5 ${tone}`}>{icon}</div><div><p className={`text-2xl font-semibold ${tone}`}>{value.toLocaleString("th-TH")}</p><p className="text-xs text-violet-100/45">{label}</p></div></CardContent></Card>; }
