import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Boxes, CheckCircle2, RefreshCw, Tags, XCircle } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

export default function MappingDashboard() {
  const query = trpc.stock.mappingSummary.useQuery(undefined, { refetchInterval: 60_000 });
  const data = query.data;
  const products = data?.products ?? [];
  const [mappingFilter, setMappingFilter] = useState<"all" | "missing_alias">("all");
  const visibleProducts = mappingFilter === "missing_alias" ? products.filter(item => !item.aliases?.trim()) : products;
  return <div className="min-h-[calc(100vh-2rem)] space-y-5 bg-[#09070d] p-2 text-white sm:p-4 lg:p-6">
    <header className="rounded-3xl border border-violet-500/20 bg-[#100c19] p-6 shadow-2xl shadow-violet-950/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-fuchsia-300"><Tags className="h-4 w-4" /> NIGHTOPS · MAPPING DASHBOARD</div><h1 className="mt-3 text-3xl font-semibold">สรุปสถานะ Mapping สินค้า</h1><p className="mt-2 text-sm leading-6 text-violet-100/55">ตรวจ Alias ที่ผูกกับ SKU จริงจากคลังสินค้า และไล่แก้รายการที่ยังไม่พร้อมใช้งาน</p></div><div className="flex gap-2"><Link href="/stock-room"><Button variant="outline" className="border-violet-400/20 bg-violet-400/5 text-violet-100">เปิด Stock Room</Button></Link><Button variant="outline" onClick={() => query.refetch()} className="border-violet-400/20 bg-violet-400/5 text-violet-100"><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} />รีเฟรช</Button></div></div></header>
    {query.isError ? <Card className="border-red-400/25 bg-red-950/20"><CardContent className="p-5 text-sm text-red-200">โหลด Mapping ไม่สำเร็จ: {query.error.message}</CardContent></Card> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="สินค้าทั้งหมด" value={data?.total ?? 0} tone="text-white" icon={<Boxes className="h-5 w-5" />} /><Summary label="ผูก Alias แล้ว" value={data?.mapped ?? 0} tone="text-emerald-300" icon={<CheckCircle2 className="h-5 w-5" />} /><Summary label="ยังไม่มี Alias" value={data?.missingAlias ?? 0} tone="text-amber-300" icon={<XCircle className="h-5 w-5" />} /><Summary label="SKU ซ้ำ" value={data?.duplicateSku ?? 0} tone="text-red-300" icon={<AlertTriangle className="h-5 w-5" />} /><Summary label="ไม่มี SKU" value={data?.missingSku ?? 0} tone="text-red-300" icon={<AlertTriangle className="h-5 w-5" />} /></div>
    <Card className="rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">สถานะรายสินค้า</CardTitle><div className="flex rounded-xl border border-violet-500/15 bg-black/20 p-1">{([ ["all", "ทั้งหมด"], ["missing_alias", `ยังไม่มี Alias (${data?.missingAlias ?? 0})`] ] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setMappingFilter(value)} className={`rounded-lg px-3 py-1.5 text-[11px] transition ${mappingFilter === value ? "bg-amber-400/15 text-amber-200" : "text-violet-100/45 hover:text-violet-100"}`}>{label}</button>)}</div></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="border-b border-violet-500/10 text-violet-100/35"><tr><th className="p-3">สินค้า</th><th className="p-3">SKU</th><th className="p-3">Alias</th><th className="p-3">สต๊อก</th><th className="p-3">สถานะ Mapping</th><th className="p-3">จัดการ</th></tr></thead><tbody>{visibleProducts.map(item => { const ready = Boolean(item.sku && item.aliases?.trim()); return <tr key={item.id} className="border-b border-violet-500/[0.06]"><td className="p-3"><div className="flex items-center gap-2"><span className="text-lg">{item.emoji ?? "📦"}</span><span className="font-medium text-white">{item.thName || item.label}</span></div></td><td className="p-3 font-mono text-fuchsia-200">{item.sku || "ไม่มี SKU"}</td><td className="max-w-xs p-3 text-violet-100/65">{item.aliases || <span className="text-amber-300">ยังไม่มี Alias</span>}</td><td className="p-3 text-emerald-300">{item.stockQty ?? 0}</td><td className="p-3"><Badge className={ready ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-amber-400/20 bg-amber-400/10 text-amber-200"}>{ready ? "MAPPED" : "ต้องตรวจ"}</Badge></td><td className="p-3"><Link href={`/aliases?sku=${encodeURIComponent(item.sku)}`}><Button size="sm" variant="outline" className="border-fuchsia-400/20 bg-fuchsia-400/5 text-fuchsia-200">แก้ Mapping</Button></Link></td></tr>; })}</tbody></table></div>{query.isLoading ? <p className="p-8 text-center text-sm text-violet-100/40">กำลังโหลด Mapping…</p> : null}{!query.isLoading && visibleProducts.length === 0 ? <p className="p-8 text-center text-sm text-emerald-300/70">ไม่มีสินค้าที่ตรงกับตัวกรองนี้</p> : null}</CardContent></Card>
  </div>;
}

function Summary({ label, value, tone, icon }: { label: string; value: number; tone: string; icon: React.ReactNode }) { return <Card className="rounded-2xl border-violet-500/15 bg-[#100d15]"><CardContent className="flex items-center gap-3 p-4"><div className={`rounded-xl bg-violet-500/10 p-2.5 ${tone}`}>{icon}</div><div><p className={`text-2xl font-semibold ${tone}`}>{value.toLocaleString("th-TH")}</p><p className="text-xs text-violet-100/45">{label}</p></div></CardContent></Card>; }
