import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Boxes, CheckCircle2, RefreshCw } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type Bucket = "all" | "one" | "two" | "three_plus";

export default function OrderBuckets() {
  const query = trpc.orders.live.useQuery(undefined, { refetchInterval: 30_000 });
  const [bucket, setBucket] = useState<Bucket>("all");
  const orders = query.data?.orders ?? [];
  const getQty = (order: (typeof orders)[number]) => (order.total_quantity ?? order.items.reduce((sum, item) => sum + Number(item.quantity ?? item.qty ?? 1), 0)) || 1;
  const counts = useMemo(() => ({ one: orders.filter(order => getQty(order) === 1).length, two: orders.filter(order => getQty(order) === 2).length, three_plus: orders.filter(order => getQty(order) >= 3).length }), [orders]);
  const visible = bucket === "all" ? orders : orders.filter(order => bucket === "one" ? getQty(order) === 1 : bucket === "two" ? getQty(order) === 2 : getQty(order) >= 3);
  return <div className="min-h-[calc(100vh-2rem)] space-y-5 bg-[#09070d] p-2 text-white sm:p-4 lg:p-6">
    <header className="rounded-3xl border border-violet-500/20 bg-[#100c19] p-6 shadow-2xl shadow-violet-950/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-fuchsia-300"><Boxes className="h-4 w-4" /> NIGHTOPS · ORDER REVIEW QUEUE</div><h1 className="mt-3 text-3xl font-semibold">แยกออเดอร์ตามจำนวนคอต</h1><p className="mt-2 text-sm leading-6 text-violet-100/55">เป็นมุมตรวจจาก <span className="font-mono text-fuchsia-200">bb_orders</span> เดียวกัน ไม่คัดลอกหรือย้ายข้อมูลจริง</p></div><div className="flex gap-2"><Link href="/orders"><Button className="bg-gradient-to-r from-fuchsia-600 to-violet-600">ส่งเข้าห้องรวม <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Button variant="outline" onClick={() => query.refetch()} className="border-violet-400/20 bg-violet-400/5 text-violet-100"><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} />รีเฟรช</Button></div></div></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{([ ["all", "รวมทั้งหมด", orders.length, "text-white"], ["one", "1 คอต", counts.one, "text-emerald-300"], ["two", "2 คอต", counts.two, "text-amber-300"], ["three_plus", "3 คอตขึ้นไป", counts.three_plus, "text-fuchsia-300"] ] as const).map(([value, label, count, tone]) => <button key={value} type="button" onClick={() => setBucket(value)} className={`text-left ${bucket === value ? "ring-1 ring-fuchsia-400/50" : ""}`}><Card className="rounded-2xl border-violet-500/15 bg-[#100d15]"><CardContent className="p-4"><p className={`text-2xl font-semibold ${tone}`}>{count.toLocaleString("th-TH")}</p><p className="text-xs text-violet-100/45">{label}</p></CardContent></Card></button>)}</div>
    <Card className="rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader><CardTitle className="flex items-center justify-between text-base"><span>{bucket === "all" ? "ออเดอร์ทั้งหมด" : bucket === "one" ? "ออเดอร์ 1 คอต" : bucket === "two" ? "ออเดอร์ 2 คอต" : "ออเดอร์ 3 คอตขึ้นไป"}</span><Badge className="border-violet-400/20 bg-violet-400/10 text-violet-200">{visible.length} รายการ</Badge></CardTitle></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-violet-500/10 text-violet-100/35"><tr><th className="p-3">Order</th><th className="p-3">ลูกค้า</th><th className="p-3">สินค้า</th><th className="p-3">จำนวนคอต</th><th className="p-3">สถานะ</th><th className="p-3">ตรวจ/แก้</th></tr></thead><tbody>{visible.map(order => <tr key={order.order_number} className="border-b border-violet-500/[0.06]"><td className="p-3 font-mono text-fuchsia-200">{order.order_number}</td><td className="p-3 text-white">{order.customer_name || "ไม่ระบุ"}<p className="text-[10px] text-violet-100/35">{order.phone || "ไม่มีเบอร์"}</p></td><td className="max-w-sm p-3 text-violet-100/65">{order.items.map(item => item.display_for_packer || item.label_display || item.th_name || item.sku || "สินค้า").join(" · ")}</td><td className="p-3 font-semibold text-emerald-300">{getQty(order)}</td><td className="p-3"><Badge className="border-violet-400/20 bg-violet-400/10 text-violet-200">{order.order_status || order.audit_status || "รอตรวจ"}</Badge></td><td className="p-3"><Link href="/orders"><Button size="sm" variant="outline" className="border-fuchsia-400/20 bg-fuchsia-400/5 text-fuchsia-200"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />เปิดตรวจ</Button></Link></td></tr>)}</tbody></table></div>{query.isLoading ? <p className="p-8 text-center text-sm text-violet-100/40">กำลังโหลดออเดอร์…</p> : null}{!query.isLoading && visible.length === 0 ? <p className="p-8 text-center text-sm text-violet-100/40">ไม่พบออเดอร์ในกลุ่มนี้</p> : null}</CardContent></Card>
  </div>;
}
